"""Add project to WorkHistory

Revision ID: 700d35902044
Revises: f493f834625f
Create Date: 2026-02-12 22:44:24.501637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700d35902044'
down_revision: Union[str, None] = 'f493f834625f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('project', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'project')
    # ### end Alembic commands ###
