"""Update Employee level and add experience_years

Revision ID: f493f834625f
Revises: d2958bb4d8af
Create Date: 2026-02-12 22:33:00.365227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f493f834625f'
down_revision: Union[str, None] = 'd2958bb4d8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('employees')]

    with op.batch_alter_table('employees', schema=None) as batch_op:
        if 'experience_years' not in columns:
            batch_op.add_column(sa.Column('experience_years', sa.Float(), nullable=True))
        
        batch_op.alter_column('level',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Integer(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('employees', 'experience_years')
    # ### end Alembic commands ###
